[package]
name = "whatlang_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "whatlang_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
whatlang = "0.16.2"
